name: Integration Testing For Staging

on:
  pull_request:
    branches:
      develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Build app"
        run: /
          npm install
          npm run build
        
